### PR TITLE
Added and ran prettier for consistent indentation and formatting

### PR DESCRIPTION
**Pull request by RohanTalip**

### CODE REVIEW

**Comment by RohanTalip** [comment]
Let me know if you would prefer to keep single quotes: https://prettier.io/docs/en/options.html#quotes

**Comment by nothingismagick** [comment]
Well, I appreciate the gusto - but let me rebuild it for quasar 1.0 before
you do too much work here.

>

**Comment by RohanTalip** [comment]
My main goal at the moment is to make some corrections and additions to the lib/settings.js file, and I figured running prettier beforehand would be a good first step, since that file has inconsistent indentation (tabs mixed with spaces).

(FYI, the "trailingComma": "es5" setting for prettier typically results in fewer diffs going forward.)

**Comment by RohanTalip** [comment]
There should be fewer diffs now (you can select "Hide whitespace changes" in the Diff settings dropdown on the Files changed tab).

**Comment by RohanTalip** [comment]
Thanks for approving and merging my changes! 😄 

FYI, if you really want to keep the commas at the start of the require lines (instead of at the end) in lib/index.js, you can add "// prettier-ignore" as per https://prettier.io/docs/en/ignore.html ... however it's kind of non-standard, in my opinion.

**Pull request merged**
